version: "3.9"
services:
  app:
    container_name: aws-nodejs-typescript-docker-template-deploy
    build:
      context: .
      target: deploy
    image: aws-nodejs-typescript-docker-template:deploy
    environment:
      NODE_ENV: development
      STAGE: ${STAGE}
      REGION: ${REGION}
      MY_SECRET: ${MY_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
