on: push
name: test
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create test image
      run: docker-compose -f docker-compose.test.yml build
    - name: Run Test
      run: docker-compose -f docker-compose.test.yml up
      env:
        NODE_ENV: development
        STAGE: ${{secrets.STAGE}}
        REGION: ${{secrets.REGION}}
        MY_SECRET: ${MY_SECRET}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

